
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  version = "v1.13.1"
  name = "github.com/docker/docker"
  source = "https://github.com/moby/moby.git"

[[constraint]]
  name = "github.com/spf13/pflag"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"

[[constraint]]
  branch = "release-1.7"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-4.0"

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/timfallmk/go-daemon"
